### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
from scipy.stats import randint

np.__version__

'2.0.2'

### <a name='1'></a> Ćwiczenie 31
Wykonaj dwa sortowania podanej poniżej tablicy $A$:
* wierszowo (rosnąco)
* kolumnowo (rosnąco)


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.sort()_.

In [2]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

print(np.sort(A))
print(np.sort(A,axis=0))


[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


### <a name='2'></a> Ćwiczenie 32
Wytnij wszystkie elementy tablicy $A$ o wartości wyższej niż 8.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



In [3]:
A[A>8]

array([ 9.99,  9.99, 14.99])

### <a name='3'></a> Ćwiczenie 33
Podana jest poniższa tablica $A$. Zastąp elementy powyżej wartości 10 wartością stałą 10 (obcięcie wartości do 10).


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.where()_.

In [4]:
print(np.where(A> 10, 10, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99  4.99]
 [10.    2.39  7.29]]


### <a name='4'></a> Ćwiczenie 34
Poniższą dwuwymiarową tablicę $A$ przedstaw w postaci 'wypłaszczonej' jednowymiarowej tablicy.  

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Oczekiwany wynik:__


```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Wskazówka:__ Użyj funkcji _np.ravel()_.




In [5]:
np.ravel(A)

array([ 4.99,  3.49,  9.99,  1.99,  9.99,  4.99, 14.99,  2.39,  7.29])

### <a name='5'></a> Ćwiczenie 35
Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 0.0.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Oczekiwany wynik:__


```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```





__Wskazówka:__ Użyj funkcji _np.zeros_like()_.

In [6]:
print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### <a name='6'></a> Ćwiczenie 36

Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 9.99.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

__Oczekiwany wynik:__


```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```



__Wskazówka:__ Użyj funkcji _np.full_like()_.

In [7]:
print(np.full_like(A, 9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


### <a name='7'></a> Ćwiczenie 37
Zbuduj tablicę dwuwymiarową (macierz kwadratową dolną trójkątną) podnaną poniżej:


```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
__Wskazówka:__ Użyj funkcji _np.tri()_.


In [8]:
print(np.tri(5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


### <a name='8'></a> Ćwiczenie 38
Stwórz dowolną tablicę 3-wymiarową o kształcie $(2, 3, 4)$.

In [9]:
np.array([[[5,4,6,4],
           [3,2,4,2],
           [4,7,9,5]],

           [[4,6,2,4],
            [4,3,5,3],
            [5,2,4,2]]])# tutaj wpisz rozwiązanie

array([[[5, 4, 6, 4],
        [3, 2, 4, 2],
        [4, 7, 9, 5]],

       [[4, 6, 2, 4],
        [4, 3, 5, 3],
        [5, 2, 4, 2]]])

### <a name='9'></a> Ćwiczenie 39

Wygeneruj dwuwymiarową tablicę o kształcie _(200, 300)_ wypełnioną wartościami losowymi od 0 do 255 włacznie i typie danych _np.uint8_ i przypisz do zmiennej _image_.

In [10]:
image = np.random.randint(0,256,size = (200,300),dtype=np.uint8)
print(image)

[[242  14 214 ... 222 107 243]
 [ 46   9  15 ... 155  29 159]
 [215 102 242 ...  99 183  29]
 ...
 [143 101 115 ... 105 212  47]
 [ 83 231  62 ... 188  92 228]
 [112  90 242 ... 144 165 176]]
